import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Brian",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
    {
      name: "Goku",
      email: "user123@example.com",
      password: bcrypt.hashSync("12345678"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: "Cute Checker Shirt",
      slug: "cute-checker-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Cutey",
      rating: 4.5,
      numReviews: 10,
      description: "Cutest shirt ever!",
    },
    {
      // _id: "2",
      name: "Nike Gold Shoes",
      slug: "nike-gold-shoe",
      category: "Shoes",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "You will look so cool! :) It is a limited edition!",
    },
    {
      // _id: "3",
      name: "White Puma Shoes",
      slug: "white-puma-shoes",
      category: "Shoes",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Puma",
      rating: 4.5,
      numReviews: 14,
      description: "Super comfy",
    },
    {
      // _id: "4",
      name: "Comfy Brown Checker Shirt",
      slug: "brown-checker-shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "Super comfy and very beautiful colour", 
    },
  ],
};

export default data;
